/**
 * Story content, kept as data so the prose can be edited without touching the
 * scroll machinery.
 *
 * Numbered with gaps (010, 020, 030 …) so a chapter can be inserted between two
 * others without renumbering everything — the same convention the SPUN story
 * uses. `id` also becomes the anchor in the URL.
 *
 * `visual` names what the sticky panel shows while the chapter is active. Add
 * new kinds in Story.tsx's `Visual` component; the union keeps the two in sync.
 */

export type ChapterVisual =
  | { kind: 'image'; src: string; alt: string; caption?: string }
  /**
   * Frames that cross-fade as the chapter scrolls past — for an argument built
   * in steps. `note` is what shows if the images are not there yet, so the
   * chapter still reads before the artwork exists.
   */
  | {
      kind: 'sequence';
      note: string;
      frames: Array<{ src: string; alt: string; caption?: string }>;
    }
  | { kind: 'figure'; src: string; alt: string; caption?: string }
  | { kind: 'stat'; value: number; unit: string; label: string; decimals?: number }
  | { kind: 'placeholder'; note: string };

export type Chapter = {
  id: string;
  eyebrow?: string;
  title: string;
  /** Each string is one paragraph. */
  body: string[];
  visual: ChapterVisual;
};

export const CHAPTERS: Chapter[] = [
  {
    id: '010-what-we-mapped',
    eyebrow: 'The map',
    title: 'Forests are not flat',
    body: [
      'Global forest maps have mostly answered one question: is there a tree here or not. ' +
        'But a young plantation and an old-growth stand can look identical from directly above ' +
        'while storing completely different amounts of carbon and supporting completely different species.',
      'What separates them is vertical structure — how the canopy is arranged between the ground ' +
        'and the treetops. That is what this map measures, everywhere, at 10 m.',
    ],
    visual: { kind: 'placeholder', note: 'Side-by-side: same canopy cover, different vertical profile' },
  },
  {
    id: '020-how-it-is-measured',
    eyebrow: 'The method',
    title: 'Two satellites, one profile',
    body: [
      'GEDI, on the International Space Station, fires laser pulses at the canopy and records how ' +
        'the returned energy is distributed with height. It measures structure directly — but only ' +
        'along sparse tracks, sampling a fraction of the land surface.',
      'Sentinel-2 sees everywhere, every few days, but only in two dimensions.',
      'We train a model to predict the full GEDI waveform from Sentinel-2 imagery, then apply it ' +
        'globally. The result is a vertical profile for every 10 m pixel on land.',
    ],
    visual: {
      kind: 'sequence',
      note: 'Sentinel-2 tile → sparse GEDI tracks over it → predicted profile everywhere',
      frames: [
        {
          src: 'story/method-1-sentinel2.webp',
          alt: 'Sentinel-2 true-colour image of a forested area',
          caption: 'Sentinel-2 sees everywhere, every few days — but only from above.',
        },
        // Frame 2 — GEDI ground tracks over the same area — is missing on
        // purpose. It needs the GEDI data that only exists on the cluster, and
        // inventing plausible track positions for a paper's companion site
        // would be publishing invented data as measurement. Drop the file in as
        // story/method-2-gedi.webp and restore this entry between the two.
        {
          src: 'story/method-3-predicted.webp',
          alt: 'Predicted canopy structure across the whole area',
          caption: 'The model learns the link, and fills in everywhere between the tracks.',
        },
      ],
    },
  },
  {
    id: '030-relative-height',
    eyebrow: 'Reading the map',
    title: 'What RH98 means',
    body: [
      'The profile is summarised by relative height percentiles. RH98 is the height below which ' +
        '98% of the returned energy falls — in practice, the top of the canopy.',
      'Lower percentiles describe the layers underneath: RH50 sits near the middle of the canopy ' +
        'mass, RH25 in the understorey. Looking at several together is what makes structure visible ' +
        'rather than just height.',
    ],
    visual: { kind: 'placeholder', note: 'Animated: RH0 → RH100 sweeping up a profile' },
  },
  {
    id: '040-a-transect',
    eyebrow: 'An example',
    title: 'Cutting a line through the forest',
    body: [
      'Sampling the predicted profile along a line turns the map into a cross-section: the canopy ' +
        'seen from the side, kilometre after kilometre.',
      'Structure that is invisible from above — a logging road, the edge of a plantation, riparian ' +
        'forest following a river — appears immediately.',
    ],
    // Generated by scripts/generate-transect-examples.mjs; see that file for the coordinates.
    visual: {
      kind: 'figure',
      src: 'examples/transect-amazon.png',
      alt: 'Vertical profile transect across a deforestation frontier in the Amazon',
      caption: 'Transect across a deforestation frontier, Mato Grosso, Brazil',
    },
  },
  {
    id: '050-scale',
    eyebrow: 'The dataset',
    title: 'Global, at 10 metres',
    body: [
      'The map covers every Sentinel-2 tile with vegetation, at the native 10 m resolution of the ' +
        'imagery, for 2020 and 2024.',
      'It is published as cloud-optimised GeoTIFFs, so the map you are about to open is reading ' +
        'the same files anyone can download.',
    ],
    visual: { kind: 'stat', value: 18128, unit: 'tiles', label: 'Sentinel-2 tiles mapped' },
  },
  {
    id: '900-explore',
    eyebrow: 'Your turn',
    title: 'Open the map',
    body: [
      'Pick a percentile, pick a place, and click anywhere to read the profile under your cursor.',
    ],
    visual: { kind: 'placeholder', note: 'Call to action — handled by the CTA block' },
  },
];
