/**
 * Story content, kept as data so the prose can be edited without touching the
 * scroll machinery.
 *
 * Numbered with gaps (010, 020, 030 …) so a chapter can be inserted between two
 * others without renumbering everything — the same convention the SPUN story
 * uses. `id` also becomes the anchor in the URL.
 *
 * `visual` names what the sticky panel shows while the chapter is active. Add
 * new kinds in Story.tsx's `Visual` component; the union keeps the two in sync.
 */

export type ChapterVisual =
  | { kind: 'image'; src: string; alt: string; caption?: string }
  /**
   * The chapter-2 explainer, drawn and animated from real data as the chapter
   * scrolls past. Its content lives in GediShot.tsx, not here, because every
   * part of it — the beats, their captions, the geometry — is one figure.
   */
  | { kind: 'gedi-shot' }
  /** Chapter 1's pair of look-alike places. Lives in ForestPair.tsx. */
  | { kind: 'forest-pair' }
  | { kind: 'figure'; src: string; alt: string; caption?: string }
  /** Looping clip. `poster` shows before it loads and if it never plays. */
  | {
      kind: 'video';
      sources: string[];
      poster: string;
      alt: string;
      caption?: string;
    }
  | { kind: 'stat'; value: number; unit: string; label: string; decimals?: number }
  /** The closing slide's button. A deck has no footer to put it in. */
  | { kind: 'cta' }
  | { kind: 'placeholder'; note: string };

export type Chapter = {
  id: string;
  eyebrow?: string;
  title: string;
  /** Each string is one paragraph. */
  body: string[];
  visual: ChapterVisual;
};

export const CHAPTERS: Chapter[] = [
  {
    id: '010-what-we-mapped',
    eyebrow: '',
    title: 'Forests are not flat',
    body: [
      'Most forest maps answer one question: **is there a tree here or not**.',
      'But two stands can look identical from above and be nothing alike inside — different ' +
        'carbon, different species.',
      'What separates them is **vertical structure**. That is what this map measures, ' +
        'everywhere, at 10 m.',
    ],
    visual: { kind: 'forest-pair' },
  },
  {
    id: '020-how-it-is-measured',
    eyebrow: 'The method',
    title: 'Two satellites, one profile',
    body: [
      'GEDI, on the International Space Station, fires laser pulses at the canopy and records how ' +
        'the returned energy is distributed with height. It measures structure directly — but only ' +
        'along sparse tracks, sampling a fraction of the land surface.',
      'Sentinel-2 sees everywhere, every few days, but only in two dimensions.',
      'We train a model to predict the full GEDI waveform from Sentinel-2 imagery, then apply it ' +
        'globally. The result is a vertical profile for every 10 m pixel on land.',
    ],
    visual: { kind: 'gedi-shot' },
  },
  {
    id: '030-relative-height',
    eyebrow: 'Reading the map',
    title: 'What RH98 means',
    body: [
      'The profile is summarised by relative height percentiles. RH98 is the height below which ' +
        '98% of the returned energy falls — in practice, the top of the canopy.',
      'Lower percentiles describe the layers underneath: RH50 sits near the middle of the canopy ' +
        'mass, RH25 in the understorey. Looking at several together is what makes structure visible ' +
        'rather than just height.',
    ],
    visual: { kind: 'placeholder', note: 'Animated: RH0 → RH100 sweeping up a profile' },
  },
  {
    id: '040-a-transect',
    eyebrow: 'An example',
    title: 'Cutting a line through the forest',
    body: [
      'Sampling the predicted profile along a line turns the map into a cross-section: the canopy ' +
        'seen from the side, kilometre after kilometre.',
      'Structure that is invisible from above — a logging road, the edge of a plantation, riparian ' +
        'forest following a river — appears immediately.',
    ],
    // Generated by scripts/generate-transect-examples.mjs; see that file for the coordinates.
    visual: {
      kind: 'figure',
      src: 'examples/transect-amazon.webp',
      alt: 'Vertical profile transect across a deforestation frontier in the Amazon',
      caption: 'Transect across a deforestation frontier, Mato Grosso, Brazil',
    },
  },
  {
    id: '050-scale',
    eyebrow: 'The dataset',
    title: 'Global, at 10 metres',
    body: [
      'The map covers every Sentinel-2 tile with vegetation, at the native 10 m resolution of the ' +
        'imagery, for 2020 and 2024.',
      'It is published as cloud-optimised GeoTIFFs, so the map you are about to open is reading ' +
        'the same files anyone can download.',
    ],
    visual: { kind: 'stat', value: 18128, unit: 'tiles', label: 'Sentinel-2 tiles mapped' },
  },
  {
    id: '900-explore',
    eyebrow: 'Your turn',
    title: 'Open the map',
    body: [
      'Pick a percentile, pick a place, and click anywhere to read the profile under your cursor.',
    ],
    visual: { kind: 'cta' },
  },
];
